snd-soc-yamaha_ymu831-objs := ymu831.o ymu831_dbg.o \
	mcbdspdrv.o	\
	mccdspdrv.o	\
	mcdevif.o	\
	mcdevprof.o	\
	mcdriver.o	\
	mcedspdrv.o	\
	mcfdspdrv.o	\
	mcmachdep.o	\
	mcpacking.o	\
	mcparser.o	\
	mcresctrl.o	\
	mcservice.o	\
	mcdebuglog.o	\
	ymu831_dbg_sec.o

obj-$(CONFIG_SND_SOC_YAMAHA_YMU831) += snd-soc-yamaha_ymu831.o
