#if 1
/*
 * Gpio-rev00-s2plus.h
 *
 * 2011. 12.21 Sexykyu
 *
 * S2Plus H/W REV00 Board Gpio Setup
 *
 */
#ifndef __MACH_GPIO_MIDAS_H
#define __MACH_GPIO_MIDAS_H __FILE__

#include <mach/gpio.h>

extern void midas_config_gpio_table(void);
extern void midas_config_sleep_gpio_table(void);

#define GPIO_DUMMP		EXYNOS4212_GPM3(4)

/*********************** GPA0 Block *********/

#define GPIO_BT_RXD		EXYNOS4_GPA0(0)
#define GPIO_BT_RXD_AF		2

#define GPIO_BT_TXD		EXYNOS4_GPA0(1)
#define GPIO_BT_TXD_AF		2

#define GPIO_BT_CTS		EXYNOS4_GPA0(2)
#define GPIO_BT_CTS_AF		2

#define GPIO_BT_RTS		EXYNOS4_GPA0(3)
#define GPIO_BT_RTS_AF		2

#define GPIO_GPS_RXD		EXYNOS4_GPA0(4)
#define GPIO_GPS_RXD_AF		2

#define GPIO_GPS_TXD		EXYNOS4_GPA0(5)
#define GPIO_GPS_TXD_AF		2

#define GPIO_GPS_CTS		EXYNOS4_GPA0(6)
#define GPIO_GPS_CTS_AF		2

#define GPIO_GPS_RTS		EXYNOS4_GPA0(7)
#define GPIO_GPS_RTS_AF		2


/*********************** GPA1 Block *********/
#define GPIO_AP_RXD		EXYNOS4_GPA1(0)
#define GPIO_AP_TXD		EXYNOS4_GPA1(1)

#define GPIO_TSP_SDA_18V	EXYNOS4_GPA1(2)
#define GPIO_TSP_SCL_18V	EXYNOS4_GPA1(3)


/*********************** GPB Block *********/

#define GPIO_CODEC_SDA_18V	EXYNOS4_GPB(0)
#define GPIO_CODEC_SCL_18V	EXYNOS4_GPB(1)

#define GPIO_NFC_SDA_18V	EXYNOS4_GPB(2)
#define GPIO_NFC_SCL_18V	EXYNOS4_GPB(3)

#define GPIO_CAM_SPI_SCLK	EXYNOS4_GPB(4)
#define GPIO_CAM_SPI_SSN	EXYNOS4_GPB(5)
#define GPIO_CAM_SPI_MISO	EXYNOS4_GPB(6)
#define GPIO_CAM_SPI_MOSI	EXYNOS4_GPB(7)

/*********************** GPC0 Block *********/

#define GPIO_REC_PCM_CLK	EXYNOS4_GPC0(0)
#define GPIO_REC_PCM_SYNC	EXYNOS4_GPC0(2)
#define GPIO_REC_PCM_IN		EXYNOS4_GPC0(3)
#define GPIO_REC_PCM_OUT	EXYNOS4_GPC0(4)


/*********************** GPC1 Block *********/

#define GPIO_FM_I2S_CLK		EXYNOS4_GPC1(0)
#define GPIO_FM_RST		EXYNOS4_GPC1(1)
#define GPIO_FM_I2S_SYNC	EXYNOS4_GPC1(2)
#define GPIO_FM_I2S_DI		EXYNOS4_GPC1(3)
#define GPIO_FM_I2S_DO		EXYNOS4_GPC1(4)


/*********************** GPD0 Block *********/

#define GPIO_VIBTONE_PWM	EXYNOS4_GPD0(0)
#define GPIO_PMIC_SDA		EXYNOS4_GPD0(2)
#define GPIO_PMIC_SCL		EXYNOS4_GPD0(3)


/*********************** GPD1 Block *********/

#define GPIO_8M_CAM_SCL_18V	EXYNOS4_GPD1(0)
#define GPIO_8M_CAM_SDA_18V	EXYNOS4_GPD1(1)
#define GPIO_GSENSE_SDA_18V	EXYNOS4_GPD1(2)
#define GPIO_GSENSE_SCL_18V	EXYNOS4_GPD1(3)


/*********************** GPF0 Block *********/
#define GPIO_LCD_HYNC		EXYNOS4_GPF0(0)
#define GPIO_LCD_VSYNC		EXYNOS4_GPF0(1)
#define GPIO_LCD_DE		EXYNOS4_GPF0(2)
#define GPIO_LCD_PCLK		EXYNOS4_GPF0(3)
#define GPIO_LCD_D_0		EXYNOS4_GPF0(4)
#define GPIO_LCD_D_1		EXYNOS4_GPF0(5)
#define GPIO_LCD_D_2		EXYNOS4_GPF0(6)
#define GPIO_LCD_D_3		EXYNOS4_GPF0(7)


/*********************** GPF1 Block *********/
#define GPIO_LCD_D_4		EXYNOS4_GPF1(0)
#define GPIO_LCD_D_5		EXYNOS4_GPF1(1)
#define GPIO_LCD_D_6		EXYNOS4_GPF1(2)
#define GPIO_LCD_D_7		EXYNOS4_GPF1(3)
#define GPIO_LCD_D_8		EXYNOS4_GPF1(4)
#define GPIO_LCD_D_9		EXYNOS4_GPF1(5)
#define GPIO_LCD_D_10		EXYNOS4_GPF1(6)
#define GPIO_LCD_D_11		EXYNOS4_GPF1(7)

/*********************** GPF2 Block *********/
#define GPIO_LCD_D_12		EXYNOS4_GPF2(0)
#define GPIO_LCD_D_13		EXYNOS4_GPF2(1)
#define GPIO_LCD_D_14		EXYNOS4_GPF2(2)
#define GPIO_LCD_D_15		EXYNOS4_GPF2(3)
#define GPIO_LCD_D_16		EXYNOS4_GPF2(4)
#define GPIO_LCD_D_17		EXYNOS4_GPF2(5)
#define GPIO_LCD_D_18		EXYNOS4_GPF2(6)
#define GPIO_LCD_D_19		EXYNOS4_GPF2(7)


/*********************** GPF3 Block *********/
#define GPIO_LCD_D_20		EXYNOS4_GPF3(0)
#define GPIO_LCD_D_21		EXYNOS4_GPF3(1)
#define GPIO_LCD_D_22		EXYNOS4_GPF3(2)
#define GPIO_LCD_D_23		EXYNOS4_GPF3(3)
#define GPIO_MHL_RST		EXYNOS4_GPF3(4)
#define GPIO_MHL_INT		EXYNOS4_GPF3(5)
#define GPIO_MHL_INT_AF		S3C_GPIO_SFN(0xF)


/*********************** GPJ0 Block *********/
#define GPIO_WLAN_EN		EXYNOS4212_GPJ0(0)
#define GPIO_WLAN_EN_AF		1
#define GPIO_USB_SEL		EXYNOS4212_GPJ0(1)
#define GPIO_EAR_MIC_BIAS_EN	EXYNOS4212_GPJ0(2)
#define GPIO_CODEC_LDO_EN	EXYNOS4212_GPJ0(4)
#define GPIO_WM8994_LDO		EXYNOS4212_GPJ0(4) /*old name*/
#define GPIO_PS_ALS_EN		EXYNOS4212_GPJ0(5)
#define GPIO_MSENSOR_INT	EXYNOS4212_GPJ0(7)

/*********************** GPJ1 Block *********/
#define GPIO_3_TOUCH_INT	EXYNOS4212_GPJ1(0)
#define GPIO_CAM_MCLK		EXYNOS4212_GPJ1(3)
#define GPIO_MHL_WAKE_UP	EXYNOS4212_GPJ1(4)


/*********************** GPK0 Block *********/
#define GPIO_NAND_CLK		EXYNOS4_GPK0(0)
#define GPIO_NAND_CMD		EXYNOS4_GPK0(1)
#define GPIO_eMMC_EN		EXYNOS4_GPK0(2)
#define GPIO_NAND_D_0		EXYNOS4_GPK0(3)
#define GPIO_NAND_D_1		EXYNOS4_GPK0(4)
#define GPIO_NAND_D_2		EXYNOS4_GPK0(5)
#define GPIO_NAND_D_3		EXYNOS4_GPK0(6)


/*********************** GPK1 Block *********/
#define GPIO_NAND_D_4		EXYNOS4_GPK1(3)
#define GPIO_NAND_D_5		EXYNOS4_GPK1(4)
#define GPIO_NAND_D_6		EXYNOS4_GPK1(5)
#define GPIO_NAND_D_7		EXYNOS4_GPK1(6)


/*********************** GPK2 Block *********/
#define GPIO_T_FLASH_CLK	EXYNOS4_GPK2(0)
#define GPIO_T_FLASH_CMD	EXYNOS4_GPK2(1)

#define GPIO_T_FLASH_D_0	EXYNOS4_GPK2(3)
#define GPIO_T_FLASH_D_1	EXYNOS4_GPK2(4)
#define GPIO_T_FLASH_D_2	EXYNOS4_GPK2(5)
#define GPIO_T_FLASH_D_3	EXYNOS4_GPK2(6)

/*********************** GPK3 Block *********/
#define GPIO_WLAN_SDIO_CLK	EXYNOS4_GPK3(0)
#define GPIO_WLAN_SDIO_CLK_AF	2
#define GPIO_WLAN_SDIO_CMD	EXYNOS4_GPK3(1)
#define GPIO_WLAN_SDIO_CMD_AF	2
#define GPIO_WLAN_SDIO_D0	EXYNOS4_GPK3(3)
#define GPIO_WLAN_SDIO_D0_AF	2
#define GPIO_WLAN_SDIO_D1	EXYNOS4_GPK3(4)
#define GPIO_WLAN_SDIO_D1_AF	2
#define GPIO_WLAN_SDIO_D2	EXYNOS4_GPK3(5)
#define GPIO_WLAN_SDIO_D2_AF	2
#define GPIO_WLAN_SDIO_D3	EXYNOS4_GPK3(6)
#define GPIO_WLAN_SDIO_D3_AF	2

/*********************** GPL0 Block *********/
#define GPIO_BUCK2_SEL		EXYNOS4_GPL0(1)
#define GPIO_BUCK3_SEL		EXYNOS4_GPL0(2)
#define GPIO_BUCK4_SEL		EXYNOS4_GPL0(3)
#define GPIO_HDMI_EN		EXYNOS4_GPL0(4)
#define GPIO_BT_EN		EXYNOS4_GPL0(6)

/*********************** GPL1 Block *********/
#define GPIO_PS_ALS_SCL_18V	EXYNOS4_GPL1(0)
#define GPIO_PS_ALS_SDA_18V	EXYNOS4_GPL1(1)
#define GPIO_RGB_SCL_1_8V	EXYNOS4_GPL1(0)
#define GPIO_RGB_SDA_1_8V	EXYNOS4_GPL1(1)

/*********************** GPL2 Block *********/
#define GPIO_GYRO_DE		EXYNOS4_GPL2(0)
#define GPIO_GPS_nRST		EXYNOS4_GPL2(1)
#define GPIO_GPS_PWR_EN		EXYNOS4_GPL2(2)
#define GPIO_WLAN_WAKE		EXYNOS4_GPL2(3)
#define GPIO_CHG_EN		EXYNOS4_GPL2(4)
#define GPIO_PHONE_ON		EXYNOS4_GPL2(5)
#define GPIO_NFC_EN		EXYNOS4_GPL2(6)
#define GPIO_NFC_FIRMWARE	EXYNOS4_GPL2(7)


/*********************** GPM0 Block *********/
#define GPIO_NFC_CLK_REQ	EXYNOS4212_GPM0(0)
#define GPIO_ISP_STANDBY	EXYNOS4212_GPM0(1)
#define GPIO_ISP_CORE_EN	EXYNOS4212_GPM0(3)
#define GPIO_CAM_VT_nSTBY	EXYNOS4212_GPM0(5)
#define GPIO_TA_nCONNECTED	EXYNOS4212_GPM0(6)
#define GPIO_CHG_ING_N		EXYNOS4212_GPM0(7)


/*********************** GPM1 Block *********/
#define GPIO_HW_REV0		EXYNOS4212_GPM1(2)
#define GPIO_HW_REV1		EXYNOS4212_GPM1(3)
#define GPIO_HW_REV2		EXYNOS4212_GPM1(4)
#define GPIO_HW_REV3		EXYNOS4212_GPM1(5)
#define GPIO_CAM_VT_nRST	EXYNOS4212_GPM1(6)


/*********************** GPM2 Block *********/

#define GPIO_IF_PMIC_SDA	EXYNOS4212_GPM2(0)
#define GPIO_IF_PMIC_SCL	EXYNOS4212_GPM2(1)
#define GPIO_TP_VT_CAM_MCLK	EXYNOS4212_GPM2(2)
#define GPIO_TSP_INT		EXYNOS4212_GPM2(3)
#define GPIO_SUSPEND_REQUEST	EXYNOS4212_GPM2(4)


/*********************** GPM3 Block *********/
#define GPIO_PMIC_DVS1		EXYNOS4212_GPM3(0)
#define GPIO_PMIC_DVS2		EXYNOS4212_GPM3(1)
#define GPIO_PMIC_DVS3		EXYNOS4212_GPM3(2)
#define GPIO_CP_REQ_RESET	EXYNOS4212_GPM3(3)


/*********************** GPM4 Block *********/
#define GPIO_3_TOUCH_SCL	EXYNOS4212_GPM4(0)
#define GPIO_3_TOUCH_SDA	EXYNOS4212_GPM4(1)
#define GPIO_VT_CAM_SCL_18V	EXYNOS4212_GPM4(2)
#define GPIO_VT_CAM_SDA_18V	EXYNOS4212_GPM4(3)

#define GPIO_MIC_BIAS_EN	EXYNOS4212_GPM4(5)
#define GPIO_MIC_BIAS_EN_00	EXYNOS4212_GPM4(5)
#define GPIO_SUB_MIC_BIAS_EN	EXYNOS4212_GPM4(6)
#define GPIO_SUB_MIC_BIAS_EN_00	EXYNOS4212_GPM4(6)


/*********************** GPX0 Block *********/
#define GPIO_ACC_INT		EXYNOS4_GPX0(0)
#define GPIO_DET_35		EXYNOS4_GPX0(1)
#define GPIO_PS_ALS_INT		EXYNOS4_GPX0(2)
#define GPIO_BOOT_MODE		EXYNOS4_GPX0(3)
#define GPIO_GYRO_INT		EXYNOS4_GPX0(4)
#define GPIO_OLED_DET		EXYNOS4_GPX0(5)
#define GPIO_PMIC_IRQ		EXYNOS4_GPX0(7)


/*********************** GPX1 Block *********/
#define GPIO_IPC_SLAVE_WAKEUP	EXYNOS4_GPX1(0)
#define GPIO_IPC_HOST_WAKEUP	EXYNOS4_GPX1(1)
#define GPIO_CP_DUMP_INT	EXYNOS4_GPX1(2)
#define GPIO_FM_INT		EXYNOS4_GPX1(3)
#define GPIO_FM_INT_REV07	EXYNOS4_GPX1(3) /*old name*/
#define GPIO_BARO_INT		EXYNOS4_GPX1(4)
#define GPIO_IF_PMIC_IRQ	EXYNOS4_GPX1(5)
#define GPIO_PHONE_ACTIVE	EXYNOS4_GPX1(6)
#define GPIO_NFC_IRQ		EXYNOS4_GPX1(7)


/*********************** GPX2 Block *********/
#define GPIO_VOL_UP		GPIO_DUMMP
#define GPIO_VOL_UP_00		EXYNOS4_GPX2(2)
#define GPIO_FUEL_ALERT		EXYNOS4_GPX2(3)
#define GPIO_ADC_INT		EXYNOS4_GPX2(4)
#define GPIO_WLAN_HOST_WAKE	EXYNOS4_GPX2(5)
#define GPIO_WLAN_HOST_WAKE_AF	0xF
#define GPIO_BT_HOST_WAKE	EXYNOS4_GPX2(6)
#define GPIO_nPOWER		EXYNOS4_GPX2(7)



/*********************** GPX3 Block *********/
#define GPIO_ISP_INT		EXYNOS4_GPX3(0)
#define GPIO_BT_WAKE		EXYNOS4_GPX3(1)
#define GPIO_CP_RST		EXYNOS4_GPX3(2)
#define GPIO_VOL_DOWN		GPIO_DUMMP
#define GPIO_VOL_DOWN_00	EXYNOS4_GPX3(3)
#define GPIO_T_FLASH_DETECT	EXYNOS4_GPX3(4)
#define GPIO_OK_KEY		EXYNOS4_GPX3(5)
#define GPIO_EAR_SEND_END	EXYNOS4_GPX3(6)

#define GPIO_HDMI_CEC		EXYNOS4_GPX3(6)
#define GPIO_HDMI_HPD		EXYNOS4_GPX3(7)

/*********************** GPY0 Block *********/
#define GPIO_ADC_SCL		EXYNOS4_GPY0(2)
#define GPIO_ADC_SDA		EXYNOS4_GPY0(3)

/*********************** GPY2 Block *********/
#define GPIO_TF_EN		EXYNOS4_GPY2(0)
#define GPIO_BSENSE_SDA_18V	EXYNOS4_GPY2(2)
#define GPIO_BSENSE_SCL_18V	EXYNOS4_GPY2(3)
#define GPIO_MSENSOR_SDA_18V	EXYNOS4_GPY2(4)
#define GPIO_MSENSOR_SCL_18V	EXYNOS4_GPY2(5)


/*********************** GPY3 Block *********/

#define GPIO_MHL_SDA_1_8V	EXYNOS4_GPY3(0)
#define GPIO_MHL_SDA_1_8V_00	EXYNOS4_GPB(2)
#define GPIO_LCD_SCLK		EXYNOS4_GPY3(1)
#define GPIO_MHL_SCL_1_8V	EXYNOS4_GPY3(2)
#define GPIO_MHL_SCL_1_8V_00	EXYNOS4_GPB(3)
#define GPIO_LCD_SDI		EXYNOS4_GPY3(3)
#define GPIO_OLED_ID		EXYNOS4_GPY3(4)
#define GPIO_ACTIVE_STATE	EXYNOS4_GPY3(5)
#define GPIO_ISP_RESET		EXYNOS4_GPY3(7)


/*********************** GPY4 Block *********/
#define GPIO_FUEL_SDA		EXYNOS4_GPY4(0)
#define GPIO_FUEL_SCL		EXYNOS4_GPY4(1)
#define GPIO_PDA_ACTIVE	EXYNOS4_GPY4(2)
#define GPIO_LCD_nCS		EXYNOS4_GPY4(3)
#define GPIO_3_TOUCH_EN	EXYNOS4_GPY4(4)
#define GPIO_MLCD_RST		EXYNOS4_GPY4(5)
#define GPIO_MHL_SEL		EXYNOS4_GPY4(6)
#define GPIO_UART_SEL		EXYNOS4_GPY4(7)


/****************** DUMMP ********************/
#define GPIO_MHL_DSDA_2_8V	GPIO_DUMMP
#define GPIO_MHL_DSCL_2_8V	GPIO_DUMMP
#define GPIO_WPC_INT		GPIO_DUMMP
#define GPIO_OTG_EN		GPIO_DUMMP /*don't used pin*/
#define GPIO_CAM_IO_EN		GPIO_DUMMP
#define GPIO_VTCAM_MCLK		GPIO_DUMMP
#define GPIO_CAM_AF_EN		GPIO_DUMMP
#define GPIO_FLM_RXD		GPIO_DUMMP
#define GPIO_FLM_RXD_AF		2
#define GPIO_FLM_TXD		GPIO_DUMMP
#define GPIO_FLM_TXD_AF		2
#define GPIO_GPS_CNTL		GPIO_DUMMP
#define GPIO_PS_ALS_SDA_28V	GPIO_DUMMP
#define GPIO_PS_ALS_SCL_28V	GPIO_DUMMP
#define MHL_INT_IRQ		gpio_to_irq(GPIO_MHL_INT)
#define MHL_WAKEUP_IRQ		gpio_to_irq(GPIO_MHL_WAKE_UP)
#define IRQ_BT_HOST_WAKE	IRQ_EINT(22)



#endif /* __MACH_GPIO_MIDAS_H */

#else

/* linux/arch/arm/mach-exynos/include/mach/gpio-exynos4.h
 *
 * Copyright (c) 2010-2011 Samsung Electronics Co., Ltd.
 *		http://www.samsung.com
 *
 * S2Plus GPIO common lib support
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *  
 */
#ifndef __MACH_GPIO_MIDAS_H
#define __MACH_GPIO_MIDAS_H __FILE__

#include <mach/gpio.h>

extern void midas_config_gpio_table(void);
extern void midas_config_sleep_gpio_table(void);

#define GPIO_DUMMP		EXYNOS4212_GPM3(4)


#define GPIO_BT_RXD		EXYNOS4_GPA0(0)
#define GPIO_BT_RXD_AF		2

#define GPIO_BT_TXD		EXYNOS4_GPA0(1)
#define GPIO_BT_TXD_AF		2

#define GPIO_BT_CTS		EXYNOS4_GPA0(2)
#define GPIO_BT_CTS_AF		2

#define GPIO_BT_RTS		EXYNOS4_GPA0(3)
#define GPIO_BT_RTS_AF		2

#define GPIO_GPS_RXD		EXYNOS4_GPA0(4)
#define GPIO_GPS_RXD_AF		2

#define GPIO_GPS_TXD		EXYNOS4_GPA0(5)
#define GPIO_GPS_TXD_AF		2

#define GPIO_GPS_CTS		EXYNOS4_GPA0(6)
#define GPIO_GPS_CTS_AF		2

#define GPIO_GPS_RTS		EXYNOS4_GPA0(7)
#define GPIO_GPS_RTS_AF		2


#define GPIO_AP_RXD		EXYNOS4_GPA1(0)
#define GPIO_AP_TXD		EXYNOS4_GPA1(1)

#define GPIO_TSP_SDA_18V	EXYNOS4_GPA1(2)
#define GPIO_TSP_SCL_18V	EXYNOS4_GPA1(3)



#define GPIO_CODEC_SDA_18V	EXYNOS4_GPB(0)
#define GPIO_CODEC_SCL_18V	EXYNOS4_GPB(1)

#define GPIO_NFC_SDA_18V	EXYNOS4_GPB(2)
#define GPIO_NFC_SCL_18V	EXYNOS4_GPB(3)

#define GPIO_CAM_SPI_SCLK	EXYNOS4_GPB(4)
#define GPIO_CAM_SPI_SSN	EXYNOS4_GPB(5)
#define GPIO_CAM_SPI_MISO	EXYNOS4_GPB(6)
#define GPIO_CAM_SPI_MOSI	EXYNOS4_GPB(7)


#define GPIO_REC_PCM_CLK	EXYNOS4_GPC0(0)
#define GPIO_REC_PCM_SYNC	EXYNOS4_GPC0(2)
#define GPIO_REC_PCM_IN		EXYNOS4_GPC0(3)
#define GPIO_REC_PCM_OUT	EXYNOS4_GPC0(4)



#define GPIO_FM_I2S_CLK		EXYNOS4_GPC1(0)
#define GPIO_FM_RST		EXYNOS4_GPC1(1)
#define GPIO_FM_I2S_SYNC	EXYNOS4_GPC1(2)
#define GPIO_FM_I2S_DI		EXYNOS4_GPC1(3)
#define GPIO_FM_I2S_DO		EXYNOS4_GPC1(4)



#define GPIO_VIBTONE_PWM	EXYNOS4_GPD0(0)
#define GPIO_PMIC_SDA		EXYNOS4_GPD0(2)
#define GPIO_PMIC_SCL		EXYNOS4_GPD0(3)



#define GPIO_8M_CAM_SCL_18V	EXYNOS4_GPD1(0)
#define GPIO_8M_CAM_SDA_18V	EXYNOS4_GPD1(1)
#define GPIO_GSENSE_SDA_18V	EXYNOS4_GPD1(2)
#define GPIO_GSENSE_SCL_18V	EXYNOS4_GPD1(3)


#define GPIO_LCD_HYNC		EXYNOS4_GPF0(0)
#define GPIO_LCD_VSYNC		EXYNOS4_GPF0(1)
#define GPIO_LCD_DE		EXYNOS4_GPF0(2)
#define GPIO_LCD_PCLK		EXYNOS4_GPF0(3)
#define GPIO_LCD_D_0		EXYNOS4_GPF0(4)
#define GPIO_LCD_D_1		EXYNOS4_GPF0(5)
#define GPIO_LCD_D_2		EXYNOS4_GPF0(6)
#define GPIO_LCD_D_3		EXYNOS4_GPF0(7)


#define GPIO_LCD_D_4		EXYNOS4_GPF1(0)
#define GPIO_LCD_D_5		EXYNOS4_GPF1(1)
#define GPIO_LCD_D_6		EXYNOS4_GPF1(2)
#define GPIO_LCD_D_7		EXYNOS4_GPF1(3)
#define GPIO_LCD_D_8		EXYNOS4_GPF1(4)
#define GPIO_LCD_D_9		EXYNOS4_GPF1(5)
#define GPIO_LCD_D_10		EXYNOS4_GPF1(6)
#define GPIO_LCD_D_11		EXYNOS4_GPF1(7)

#define GPIO_LCD_D_12		EXYNOS4_GPF2(0)
#define GPIO_LCD_D_13		EXYNOS4_GPF2(1)
#define GPIO_LCD_D_14		EXYNOS4_GPF2(2)
#define GPIO_LCD_D_15		EXYNOS4_GPF2(3)
#define GPIO_LCD_D_16		EXYNOS4_GPF2(4)
#define GPIO_LCD_D_17		EXYNOS4_GPF2(5)
#define GPIO_LCD_D_18		EXYNOS4_GPF2(6)
#define GPIO_LCD_D_19		EXYNOS4_GPF2(7)


#define GPIO_LCD_D_20		EXYNOS4_GPF3(0)
#define GPIO_LCD_D_21		EXYNOS4_GPF3(1)
#define GPIO_LCD_D_22		EXYNOS4_GPF3(2)
#define GPIO_LCD_D_23		EXYNOS4_GPF3(3)
#define GPIO_MHL_RST		EXYNOS4_GPF3(4)
#define GPIO_MHL_INT		EXYNOS4_GPF3(5)
#define GPIO_MHL_INT_AF		S3C_GPIO_SFN(0xF)


#define GPIO_WLAN_EN		EXYNOS4212_GPJ0(0)
#define GPIO_WLAN_EN_AF		1
#define GPIO_USB_SEL		EXYNOS4212_GPJ0(1)
#define GPIO_EAR_MIC_BIAS_EN	EXYNOS4212_GPJ0(2)
#define GPIO_CODEC_LDO_EN	EXYNOS4212_GPJ0(4)
#define GPIO_WM8994_LDO		EXYNOS4212_GPJ0(4) 
#define GPIO_PS_ALS_EN		EXYNOS4212_GPJ0(5)
#define GPIO_MSENSOR_INT	EXYNOS4212_GPJ0(7)

#define GPIO_3_TOUCH_INT	EXYNOS4212_GPJ1(0)
#define GPIO_CAM_MCLK		EXYNOS4212_GPJ1(3)
#define GPIO_MHL_WAKE_UP	EXYNOS4212_GPJ1(4)


#define GPIO_NAND_CLK		EXYNOS4_GPK0(0)
#define GPIO_NAND_CMD		EXYNOS4_GPK0(1)
#define GPIO_eMMC_EN		EXYNOS4_GPK0(2)
#define GPIO_NAND_D_0		EXYNOS4_GPK0(3)
#define GPIO_NAND_D_1		EXYNOS4_GPK0(4)
#define GPIO_NAND_D_2		EXYNOS4_GPK0(5)
#define GPIO_NAND_D_3		EXYNOS4_GPK0(6)


#define GPIO_NAND_D_4		EXYNOS4_GPK1(3)
#define GPIO_NAND_D_5		EXYNOS4_GPK1(4)
#define GPIO_NAND_D_6		EXYNOS4_GPK1(5)
#define GPIO_NAND_D_7		EXYNOS4_GPK1(6)


#define GPIO_T_FLASH_CLK	EXYNOS4_GPK2(0)
#define GPIO_T_FLASH_CMD	EXYNOS4_GPK2(1)

#define GPIO_T_FLASH_D_0	EXYNOS4_GPK2(3)
#define GPIO_T_FLASH_D_1	EXYNOS4_GPK2(4)
#define GPIO_T_FLASH_D_2	EXYNOS4_GPK2(5)
#define GPIO_T_FLASH_D_3	EXYNOS4_GPK2(6)

#define GPIO_WLAN_SDIO_CLK	EXYNOS4_GPK3(0)
#define GPIO_WLAN_SDIO_CLK_AF	2
#define GPIO_WLAN_SDIO_CMD	EXYNOS4_GPK3(1)
#define GPIO_WLAN_SDIO_CMD_AF	2
#define GPIO_WLAN_SDIO_D0	EXYNOS4_GPK3(3)
#define GPIO_WLAN_SDIO_D0_AF	2
#define GPIO_WLAN_SDIO_D1	EXYNOS4_GPK3(4)
#define GPIO_WLAN_SDIO_D1_AF	2
#define GPIO_WLAN_SDIO_D2	EXYNOS4_GPK3(5)
#define GPIO_WLAN_SDIO_D2_AF	2
#define GPIO_WLAN_SDIO_D3	EXYNOS4_GPK3(6)
#define GPIO_WLAN_SDIO_D3_AF	2

#define GPIO_BUCK2_SEL		EXYNOS4_GPL0(1)
#define GPIO_BUCK3_SEL		EXYNOS4_GPL0(2)
#define GPIO_BUCK4_SEL		EXYNOS4_GPL0(3)
#define GPIO_HDMI_EN		EXYNOS4_GPL0(4)
#define GPIO_BT_EN		EXYNOS4_GPL0(6)

#define GPIO_PS_ALS_SCL_18V	EXYNOS4_GPL1(0)
#define GPIO_PS_ALS_SDA_18V	EXYNOS4_GPL1(1)
#define GPIO_RGB_SCL_1_8V	EXYNOS4_GPL1(0)
#define GPIO_RGB_SDA_1_8V	EXYNOS4_GPL1(1)

#define GPIO_GYRO_DE		EXYNOS4_GPL2(0)
#define GPIO_GPS_nRST		EXYNOS4_GPL2(1)
#define GPIO_GPS_PWR_EN		EXYNOS4_GPL2(2)
#define GPIO_WLAN_WAKE		EXYNOS4_GPL2(3)
#define GPIO_PHONE_ON		EXYNOS4_GPL2(5)
#define GPIO_NFC_EN		EXYNOS4_GPL2(6)
#define GPIO_NFC_FIRMWARE	EXYNOS4_GPL2(7)


#define GPIO_NFC_CLK_REQ	EXYNOS4212_GPM0(0)
#define GPIO_ISP_STANDBY	EXYNOS4212_GPM0(1)
#define GPIO_ISP_CORE_EN	EXYNOS4212_GPM0(3)
#define GPIO_CAM_VT_nSTBY	EXYNOS4212_GPM0(5)


#define GPIO_HW_REV0		EXYNOS4212_GPM1(2)
#define GPIO_HW_REV1		EXYNOS4212_GPM1(3)
#define GPIO_HW_REV2		EXYNOS4212_GPM1(4)
#define GPIO_HW_REV3		EXYNOS4212_GPM1(5)
#define GPIO_CAM_VT_nRST	EXYNOS4212_GPM1(6)



#define GPIO_IF_PMIC_SDA	EXYNOS4212_GPM2(0)
#define GPIO_IF_PMIC_SCL	EXYNOS4212_GPM2(1)
#define GPIO_TP_VT_CAM_MCLK	EXYNOS4212_GPM2(2)
#define GPIO_TSP_INT		EXYNOS4212_GPM2(3)
#define GPIO_SUSPEND_REQUEST	EXYNOS4212_GPM2(4)


#define GPIO_PMIC_DVS1		EXYNOS4212_GPM3(0)
#define GPIO_PMIC_DVS2		EXYNOS4212_GPM3(1)
#define GPIO_PMIC_DVS3		EXYNOS4212_GPM3(2)
#define GPIO_CP_REQ_RESET	EXYNOS4212_GPM3(3)


#define GPIO_3_TOUCH_SCL	EXYNOS4212_GPM4(0)
#define GPIO_3_TOUCH_SDA	EXYNOS4212_GPM4(1)
#define GPIO_VT_CAM_SCL_18V	EXYNOS4212_GPM4(2)
#define GPIO_VT_CAM_SDA_18V	EXYNOS4212_GPM4(3)

#define GPIO_MIC_BIAS_EN	EXYNOS4212_GPM4(5)
#define GPIO_MIC_BIAS_EN_00	EXYNOS4212_GPM4(5)
#define GPIO_SUB_MIC_BIAS_EN	EXYNOS4212_GPM4(6)
#define GPIO_SUB_MIC_BIAS_EN_00	EXYNOS4212_GPM4(6)


#define GPIO_ACC_INT		EXYNOS4_GPX0(0)
#define GPIO_DET_35		EXYNOS4_GPX0(1)
#define GPIO_PS_ALS_INT		EXYNOS4_GPX0(2)
#define GPIO_BOOT_MODE		EXYNOS4_GPX0(3)
#define GPIO_GYRO_INT		EXYNOS4_GPX0(4)
#define GPIO_OLED_DET		EXYNOS4_GPX0(5)
#define GPIO_PMIC_IRQ		EXYNOS4_GPX0(7)


#define GPIO_IPC_SLAVE_WAKEUP	EXYNOS4_GPX1(0)
#define GPIO_IPC_HOST_WAKEUP	EXYNOS4_GPX1(1)
#define GPIO_CP_DUMP_INT	EXYNOS4_GPX1(2)
#define GPIO_FM_INT		EXYNOS4_GPX1(3)
#define GPIO_FM_INT_REV07	EXYNOS4_GPX1(3) 
#define GPIO_BARO_INT		EXYNOS4_GPX1(4)
#define GPIO_IF_PMIC_IRQ	EXYNOS4_GPX1(5)
#define GPIO_PHONE_ACTIVE	EXYNOS4_GPX1(6)
#define GPIO_NFC_IRQ		EXYNOS4_GPX1(7)


#define GPIO_VOL_UP		GPIO_DUMMP
#define GPIO_VOL_UP_00		EXYNOS4_GPX2(2)
#define GPIO_FUEL_ALERT		EXYNOS4_GPX2(3)
#define GPIO_ADC_INT		EXYNOS4_GPX2(4)
#define GPIO_WLAN_HOST_WAKE	EXYNOS4_GPX2(5)
#define GPIO_WLAN_HOST_WAKE_AF	0xF
#define GPIO_BT_HOST_WAKE	EXYNOS4_GPX2(6)
#define GPIO_nPOWER		EXYNOS4_GPX2(7)



#define GPIO_WPC_INT		EXYNOS4_GPX3(0)
#define GPIO_BT_WAKE		EXYNOS4_GPX3(1)
#define GPIO_CP_RST		EXYNOS4_GPX3(2)
#define GPIO_VOL_DOWN		GPIO_DUMMP
#define GPIO_VOL_DOWN_00	EXYNOS4_GPX3(3)
#define GPIO_T_FLASH_DETECT	EXYNOS4_GPX3(4)
#define GPIO_OK_KEY		EXYNOS4_GPX3(5)
#define GPIO_EAR_SEND_END	EXYNOS4_GPX3(6)

#define GPIO_HDMI_CEC		EXYNOS4_GPX3(6)
#define GPIO_HDMI_HPD		EXYNOS4_GPX3(7)


#define GPIO_ADC_SCL		EXYNOS4_GPY0(2)
#define GPIO_ADC_SDA		EXYNOS4_GPY0(3)


#define GPIO_TF_EN		EXYNOS4_GPY2(0)
#define GPIO_BSENSE_SDA_18V	EXYNOS4_GPY2(2)
#define GPIO_BENSE_SCL_18V	EXYNOS4_GPY2(3)
#define GPIO_MSENSOR_SDA_18V	EXYNOS4_GPY2(4)
#define GPIO_MSENSOR_SCL_18V	EXYNOS4_GPY2(5)



#define GPIO_MHL_SDA_1_8V	GPIO_DUMMP
#define GPIO_MHL_SDA_1_8V_00	EXYNOS4_GPY3(0)
#define GPIO_LCD_SCLK		EXYNOS4_GPY3(1)
#define GPIO_MHL_SCL_1_8V	GPIO_DUMMP
#define GPIO_MHL_SCL_1_8V_00	EXYNOS4_GPY3(2)
#define GPIO_LCD_SDI		EXYNOS4_GPY3(3)
#define GPIO_OLED_ID		EXYNOS4_GPY3(4)
#define GPIO_ACTIVE_STATE	EXYNOS4_GPY3(5)
#define GPIO_ISP_RESET		EXYNOS4_GPY3(7)


#define GPIO_FUEL_SDA		EXYNOS4_GPY4(0)
#define GPIO_FUEL_SCL		EXYNOS4_GPY4(1)
#define GPIO_PDA_ACTIVE	EXYNOS4_GPY4(2)
#define GPIO_LCD_nCS		EXYNOS4_GPY4(3)
#define GPIO_3_TOUCH_EN	EXYNOS4_GPY4(4)
#define GPIO_MLCD_RST		EXYNOS4_GPY4(5)
#define GPIO_MHL_SEL		EXYNOS4_GPY4(6)
#define GPIO_UART_SEL		EXYNOS4_GPY4(7)



#define GPIO_MHL_DSCL_2_8V	GPIO_DUMMP
#define GPIO_MHL_DSDA_2_8V	GPIO_DUMMP
#define GPIO_OTG_EN		GPIO_DUMMP 
#define GPIO_CAM_IO_EN		GPIO_DUMMP
#define GPIO_VTCAM_MCLK		GPIO_DUMMP
#define GPIO_CAM_AF_EN		GPIO_DUMMP
#define GPIO_FLM_RXD		GPIO_DUMMP
#define GPIO_FLM_RXD_AF		2
#define GPIO_FLM_TXD		GPIO_DUMMP
#define GPIO_FLM_TXD_AF		2
#define GPIO_GPS_CNTL		GPIO_DUMMP
#define GPIO_PS_ALS_SDA_28V	GPIO_DUMMP
#define GPIO_PS_ALS_SCL_28V	GPIO_DUMMP
#define MHL_INT_IRQ		gpio_to_irq(GPIO_MHL_INT)
#define MHL_WAKEUP_IRQ		gpio_to_irq(GPIO_MHL_WAKE_UP)
#define IRQ_BT_HOST_WAKE	IRQ_EINT(22)



#endif /* __MACH_GPIO_MIDAS_H */

#endif
