#
# Makefile for the vibrator driver ICs with vibrator driver
#

obj-$(CONFIG_MOTOR_DRV_MAX8997)		+= max8997_vibrator.o
obj-$(CONFIG_MOTOR_DRV_MAX77693)	+= max77693_haptic.o
obj-$(CONFIG_MOTOR_DRV_ISA1200)		+= isa1200_vibrator.o

obj-$(CONFIG_VIBETONZ) 			+= vibrator.o
vibrator-objs 				+= tspdrv.o
