#ifndef COMPAT_AUTOCONF_INCLUDED
#define COMPAT_AUTOCONF_INCLUDED

/*
 * This is an example of a compat autconf header file that gets
 * automatically generated by your projet. You will only need this
 * if you are working with a lot of config options.
 *
 * Your project will likely just override this, or leave this as-is.
 */

/*
 * Example automatically generated C config: don't edit
 * Thu Dec 10 10:34:11 PST 2009
 * compat-wireless-2.6: master-2009-11-19-5-gb4fd4dd
 * linux-2.6: next-20091208
 */
/* #define COMPAT_PROJECT_FOO_RELEASE "master-2009-11-19-5-gb4fd4dd"
#define COMPAT_UPSTREAM_FOO_KERNEL_RELEASE "next-20091208" */

/* Example kernel version minimum requirement */
/* #if (LINUX_VERSION_CODE < KERNEL_VERSION(2,6,10))
#error Compat-wireless requirement: Linux >= 2,6,10
#endif */ /* (LINUX_VERSION_CODE < KERNEL_VERSION(2,6,10) */

/* Example hard requirement */
/* #error Compat-wireless requirement:
CONFIG_WIRELESS_EXT must be enabled in your kernel
#endif */ /* CONFIG_WIRELESS_EXT */

/*
 * Example of how to match your external modules kconfig options into this.
 * You'll need something to generate this for you.
 */
/* #ifndef CONFIG_FOO_BAR
#define CONFIG_FOO_BAR 1 */

#endif /* COMPAT_AUTOCONF_INCLUDED */
