
#obj-y   += tcbd_hal.o
obj-y   += tcbd_drv_io.o
obj-y   += tcbd_drv_rf.o
obj-y   += tcbd_drv_peri.o
obj-y   += tcbd_drv_dual.o
obj-y   += tcbd_drv_ip.o
obj-y   += tcbd_api_common.o

obj-y   += tcbd_diagnosis/
obj-y   += tcbd_stream_parser/
obj-y   += tcpal_linux/
obj-y   += tcc_fic_decoder/

ccflags-y += -Idrivers/media/tdmb/tcc3170/inc
ccflags-y += -Idrivers/media/tdmb/tcc3170/inc/tcpal
ccflags-y += -Idrivers/media/tdmb/tcc3170/inc/tcbd_diagnosis
ccflags-y += -Idrivers/media/tdmb/tcc3170/inc/tcbd_stream_parser
ccflags-y += -Idrivers/media/tdmb/tcc3170/inc/tcc_fic_decoder
