#
# Makefile for the Cypress touchkey driver
#

obj-$(CONFIG_KEYBOARD_CYPRESS_TOUCH) += cypress-touchkey.o issp_driver_routines.o issp_main.o issp_routines.o
obj-$(CONFIG_KEYBOARD_CYPRESS_TOUCH_BLN) += cypress-touchkey-bln.o issp_driver_routines-bln.o issp_main-bln.o issp_routines.o
