
obj-y   += tcpal_irq_handler.o
obj-y   += tcpal_debug.o
obj-y   += tcpal_queue.o
obj-y   += tcpal_linux.o
obj-y   += tcpal_io_cspi.o
obj-y   += tcpal_io_i2c.o

ccflags-y += -Idrivers/media/tdmb/tcc3170/inc
ccflags-y += -Idrivers/media/tdmb/tcc3170/inc/tcpal
ccflags-y += -Idrivers/media/tdmb/tcc3170/inc/tcbd_diagnosis
ccflags-y += -Idrivers/media/tdmb/tcc3170/inc/tcbd_stream_parser
ccflags-y += -Idrivers/media/tdmb/tcc3170/inc/tcc_fic_decoder

ccflags-y += -Idrivers/media/tdmb/
