
obj-$(CONFIG_BATTERY_SAMSUNG)	+= samsung_battery.o	\
					battery-factory.o

obj-$(CONFIG_MAX8997_CHARGER)	+= max8997-charger.o

obj-$(CONFIG_BATTERY_MAX17043_FUELGAUGE)	+= max17043_fuelgauge.o
obj-$(CONFIG_BATTERY_MAX17042_FUELGAUGE)	+= max17042_fuelgauge.o
obj-$(CONFIG_BATTERY_MAX17047_FUELGAUGE)	+= max17047_fuelgauge.o
obj-$(CONFIG_BATTERY_MAX17047_C_FUELGAUGE)	+= max17047_fuelgauge_c.o

obj-$(CONFIG_BATTERY_SMB136_CHARGER)	+= smb136_charger.o
obj-$(CONFIG_BATTERY_MAX77693_CHARGER)	+= max77693_charger.o

obj-$(CONFIG_BATTERY_SAMSUNG_P1X)	+= sec_battery.o sec_fuelgauge.o

obj-$(CONFIG_FUELGAUGE_ADC)	+= adc_fuelgauge.o
obj-$(CONFIG_FUELGAUGE_MAX17042)	+= max17042_fuelgauge.o
obj-$(CONFIG_FUELGAUGE_MAX17048)	+= max17048_fuelgauge.o
obj-$(CONFIG_FUELGAUGE_MAX17050)	+= max17050_fuelgauge.o

obj-$(CONFIG_CHARGER_DUMMY)		+= dummy_charger.o
obj-$(CONFIG_CHARGER_MAX8903)		+= max8903_charger.o
obj-$(CONFIG_CHARGER_SMB328)		+= smb328_charger.o
obj-$(CONFIG_CHARGER_SMB347)		+= smb347_charger.o sec_charger.o
obj-$(CONFIG_CHARGER_SMB358)    	+= smb358_charger.o sec_charger.o
obj-$(CONFIG_CHARGER_BQ24190)		+= bq24190_charger.o 
obj-$(CONFIG_CHARGER_BQ24191)		+= bq24190_charger.o sec_charger.o
obj-$(CONFIG_CHARGER_NCP1851)		+= ncp1851_charger.o sec_charger.o
obj-$(CONFIG_CHARGER_TSU8111)		+= tsu8111_charger.o sec_charger.o

obj-$(CONFIG_CHARGER_MAX77693_BAT)	+= max77693_charger_bat.o


