obj-y += bbm.o
obj-y += dmbdrv_wrap_fc8050.o
obj-y += fc8050_bb.o
obj-y += fc8050_i2c.o
obj-y += fc8050_isr.o
obj-$(CONFIG_TDMB_SPI) += fc8050_spi.o
obj-$(CONFIG_TDMB_EBI) += fc8050_ppi.o
obj-y += fc8050_tun.o
obj-y += fci_hal.o
obj-y += fci_i2c.o
obj-y += fci_oal.o
obj-y += fci_tun.o
obj-y += fic.o
obj-y += ficdecoder.o

ccflags-y += -Idrivers/media/tdmb
