#
# Makefile for kernel IDPRAM drivers.
#
override obj-dirs = $(dir $(obj)) $(obj)/raffaello/

obj-$(CONFIG_SAMSUNG_PHONE_TTY_RAFFAELLO) +=raffaello/dpram.o
obj-$(CONFIG_SAMSUNG_PHONE_TTY_RAFFAELLO_RECOVERY) +=raffaello/dpram_recovery.o
