obj-y += bbm.o
obj-y += fc8150.o
obj-y += fc8150_bb.o
obj-y += fc8150_hpi.o
obj-y += fc8150_i2c.o
obj-y += fc8150_isr.o
obj-y += fc8150_ppi.o
obj-y += fc8150_spi.o
obj-y += fc8150_spib.o
obj-y += fc8150_tun.o
obj-y += fci_bypass.o
obj-y += fci_hal.o
obj-y += fci_i2c.o
obj-y += fci_oal.o
obj-y += fci_ringbuffer.o
obj-y += fci_tun.o

#ccflags-y += -Idrivers/media/isdbt
