obj-y += src/
#obj-y += tcbd.o

ccflags-y += -Idrivers/media/tdmb/tcc3170/inc
ccflags-y += -Idrivers/media/tdmb/tcc3170/inc/tcpal
ccflags-y += -Idrivers/media/tdmb/tcc3170/inc/tcbd_diagnosis
ccflags-y += -Idrivers/media/tdmb/tcc3170/inc/tcbd_stream_parser

