#
# Makefile for nfc devices
#

obj-$(CONFIG_PN544_NFC)		+= pn544.o
obj-$(CONFIG_PN65N_NFC)		+= pn65n.o
obj-$(CONFIG_PN547_NFC)		+= pn547.o
obj-$(CONFIG_BCM2079X_NFC)		+= bcm2079x-i2c.o
obj-$(CONFIG_SF2_NFC_TAG)		+= sf2_nfc_tag.o
