#
# Makefile for USB OTG Host Controller Drivers
#

obj-$(CONFIG_USB_S3C_OTG_HOST) += shost_hcd.o

shost_hcd-objs	+= shost_driver.o
shost_hcd-objs	+= shost_scheduler.o
shost_hcd-objs	+= shost_transferchecker.o
