# Samsung GPIO Debugging and Verification System
# Files relevant to each platform should be added at this MK file.

obj-$(CONFIG_ARCH_RHEA)   += rhea_gpio_dvs.o
obj-$(CONFIG_CPU_EXYNOS4412) += exynos4x12_gpio_dvs.o
