obj-y   += tcc_fic_decoder.o
obj-y   += tcc_fic_fig0.o
obj-y   += tcc_fic_fig1.o

ccflags-y += -Idrivers/media/tdmb/tcc3170/inc
ccflags-y += -Idrivers/media/tdmb/tcc3170/inc/tcpal
ccflags-y += -Idrivers/media/tdmb/tcc3170/inc/tcc_fic_decoder
